### ISSUE TITLE
Multiple window support

### ISSUE THREAD

**Issue by warxander** [warxander/vein#3]

**Comment by st860923** [comment]
Is it still WIP?

**Comment by warxander** [comment]
Hi,

Yes, as my freetime is very limited.

**Comment by warxander** [comment]
I think `vein` has all API needed to provide multi-window support:

* `windowRect` from `endWindow` to detect clicks for inactive windows (use natives)
* `SetScriptGfxDrawOrder` native for drawing windows in proper order
* `setNextWindowDisableInput` to disable input for inactive windows

All user needed is to create an `id` system to manage window states.
